---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  ports:
    - name: "grafana-ui"
      protocol: "TCP"
      port: 8000
      targetPort: 3000
      nodePort: 30800
  selector:
    app: grafana
