---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
spec:
  serviceName: grafana
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana-server
          image: grafana/grafana:5.2.3
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
          securityContext:
            runAsUser: 0

      volumes:
        - name: grafana-data
          hostPath:
            path: /data/grafana
            type: Directory
