---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: healths
spec:
  serviceName: healths
  replicas: 1
  selector:
    matchLabels:
      app: healths
  template:
    metadata:
      labels:
        app: healths
    spec:
      containers:
        - name: healths-server
          image: utky/healths:latest
          ports:
            - containerPort: 8080
          command: ["/opt/app/healths"]
          args: ["-i", "influxdb", "-d", "/var/lib/healths/state.json", "-p", "8080"]
          volumeMounts:
            - name: healths-data
              mountPath: /var/lib/healths
      volumes:
        - name: healths-data
          hostPath:
            path: /data/healths
            type: Directory
