---
apiVersion: v1
kind: Service
metadata:
  name: healths
spec:
  type: NodePort
  ports:
    - name: "healths-api"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 30880
  selector:
    app: healths
