---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  type: ClusterIP
  ports:
    - name: "influxdb-api"
      protocol: "TCP"
      port: 8086
      targetPort: 8086
    - name: "influxdb-ui"
      protocol: "TCP"
      port: 8083
      targetPort: 8083
  selector:
    app: influxdb
